### ISSUE TITLE
AttributeError while running 'bash run.sh'

### ISSUE THREAD

**Issue by jiminbot20** [TideDancer/interspeech21_emotion#10]
https://github.com/TideDancer/interspeech21_emotion/blob/6f5851604d5d2367016a020a11949e53f14e0129/run_emotion.py#L355

while runing 'bash run.sh', AttributeError happens like capture below

![스크린샷, 2022-07-28 16-29-15](https://user-images.githubusercontent.com/63258184/181511229-f1401656-f99c-4ed0-88d0-bbaada7ecda0.png)

so I added `use_amp = True` at _run_emotion.py_ line 313 temporarily. Is it right way to train your work?

**Comment by TideDancer** [comment]
Thanks for letting me know. It looks like the transformer lib is upgraded recently, and the "use_amp“ attribute is now replaced with  "use_cuda_amp" and "use_cpu_amp". See https://github.com/huggingface/transformers/blob/main/src/transformers/trainer.py, line 510-513.

In fact, I didn't use mixed precision training in my experiment. So you can just set a use_amp=False in line 313. If you want to enable it, you might need to test if it works with the latest version of transformer.
