### ISSUE TITLE
Model does not work on MELD dataset

### ISSUE THREAD

**Issue by wenjun90** [TideDancer/interspeech21_emotion#12]
Dear @TideDancer,

Could I ask you 2 questions?
- Firstly, the model does not work on the MELD dataset because I tested on MELD dataset but validation loss is always NaN
- Second, is it possible to add a new task that is sentiment prediction of speech?

Thank you very much,

Best regards

**Comment by TideDancer** [comment]
Sorry for the late reply. I never tested MELD dataset so I am not sure how it works. Do you need to rewrite the data_process part in the code ?

Yes it should be OK to add another task, and add the loss from that task. Ideally, you need to change the data_collator part to add another cls_label, and add them together, e.g. https://github.com/TideDancer/interspeech21_emotion/blob/main/run_emotion.py#L307 . Accordingly, the loss computation part https://github.com/TideDancer/interspeech21_emotion/blob/main/model.py#L101 also need changes.

Hope this helps.
