### ISSUE TITLE
Interpretation of emotion labels in CSVs

### ISSUE THREAD

**Issue by edwardt-sm** [TideDancer/interspeech21_emotion#18]
Hi @TideDancer,

In the provided CSVs giving the emotion labels for the dataset, the labels e0, e1, e2 and e3 are used to represent Happy, Sad, Neutral and Angry (not necessarily in that order). Could you confirm which "e#" label corresponds to which emotion label? This would be very helpful for using the model on other datasets which don't use these labels.

Many thanks!

**Comment by TideDancer** [comment]
Sorry for the late reply. Here are the labels if I recall correctly:
e0: neutral
e1: happy
e2: angry 
e3: sad

**Comment by edwardt-sm** [comment]
Thanks so much!

**Comment by TideDancer** [comment]
No problem. I am closing this issue.
