### ISSUE TITLE
Remove text processing from inference

### ISSUE THREAD

**Issue by ElizavetaSedova** [TideDancer/interspeech21_emotion#8]
Hello, great job!
You have implemented text processing in the inference code, so testing is not fast. As I understand it, a text does not affect the result of testing. Do you plan to create inference without using text? It seems to me that this could significantly speed up the testing process.

**Comment by TideDancer** [comment]
Hi, Thank you for your interests!
I have modified the code to remove the text processing part during inference time. Thanks for this great suggestion. Please check the latest code and let me know if you have other questions.
